### ISSUE TITLE
morning session code review 19-7-2022

### ISSUE THREAD

**Issue by aizjicod** [Nyame-Wolf/To-Do-list#11]
good job so far 💯 
there are some things that can be improved please read the following examples.
I saw in your code that you have a dispatch event for the click event. this can be easily done by just doing `click()`

**Comment by jaferIdrees** [comment]
**You have very nice code for testing**

- Mockinization was used in smart way 👍 
- You covered all required tests 💯 

**I have the below recommendation for you in the future**

- The idea behind testing is to test your original functions that do the required functionality, hence you need to immolate some actions to call these functions, so no need to create new functionality in your tests. 🍒

**Comment by karam084** [comment]
Great job, If possible you can use it for loop with test and call faction instead create one again.
